swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /arbol/:
    get:
      tags:
      - arbol
      description: get Arbol
      operationId: ArbolController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Arbol'
        "403":
          description: ""
    post:
      tags:
      - arbol
      description: create Arbol
      operationId: ArbolController.Create
      parameters:
      - in: body
        name: body
        description: body for Arbol content
        required: true
        schema:
          $ref: '#/definitions/models.Arbol'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Arbol'
        "403":
          description: body is empty
  /arbol/{id}:
    get:
      tags:
      - arbol
      description: get Arbol by id
      operationId: ArbolController.GetArbol
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Arbol'
        "403":
          description: :id is empty
    put:
      tags:
      - arbol
      description: update the Arbol
      operationId: ArbolController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Arbol content
        required: true
        schema:
          $ref: '#/definitions/models.Arbol'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Arbol'
        "403":
          description: :id is not int
    delete:
      tags:
      - arbol
      description: delete the Plan Arbol
      operationId: ArbolController.DeletePlan
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /formato/:
    get:
      tags:
      - formato
      description: get Formato
      operationId: FormatoController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formato'
        "403":
          description: ""
    post:
      tags:
      - formato
      description: create Formato
      operationId: FormatoController.Create
      parameters:
      - in: body
        name: body
        description: body for Formato content
        required: true
        schema:
          $ref: '#/definitions/models.Formato'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Formato'
        "403":
          description: body is empty
  /formato/{id}:
    get:
      tags:
      - formato
      description: get Formato by id
      operationId: FormatoController.GetFormato
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formato'
        "403":
          description: :id is empty
    put:
      tags:
      - formato
      description: update the Formato
      operationId: FormatoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Formato content
        required: true
        schema:
          $ref: '#/definitions/models.Formato'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formato'
        "403":
          description: :id is not int
    delete:
      tags:
      - formato
      description: delete the Formato
      operationId: FormatoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /formulacion/actualizar_actividad/{id}/{index}:
    put:
      tags:
      - formulacion
      description: put Formulacion by id
      operationId: FormulacionController.ActualizarActividad
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: path
        name: index
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty
  /formulacion/clonar_formato/{id}:
    post:
      tags:
      - formulacion
      description: post Formulacion by id
      operationId: FormulacionController.ClonarFormato
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty

  /formulacion/delete_actividad/{id}/{index}:
    put:
      tags:
      - formulacion
      description: put Formulacion by id
      operationId: FormulacionController.DeleteActividad
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: path
        name: index
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty
  /formulacion/get_all_actividades/{id}/:
    get:
      tags:
      - formulacion
      description: put Formulacion by id
      operationId: FormulacionController.GetAllActividades
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty
  /formulacion/get_plan/{id}/{index}:
    get:
      tags:
      - formulacion
      description: get Plan by id
      operationId: FormulacionController.GetPlan
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: path
        name: index
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty
  /formulacion/guardar_actividad/{id}:
    put:
      tags:
      - formulacion
      description: put Formulacion by id
      operationId: FormulacionController.GuardarActividad
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulacion'
        "403":
          description: :id is empty

definitions:
  '{}':
    title: '{}'
    type: object
  models.Arbol:
    title: Arbol
    type: object
  models.Formato:
    title: Formato
    type: object
  models.Formulacion:
    title: Formulacion
    type: object
tags:
- name: arbol
  description: |
    ArbolController operations for Arbol
- name: formato
  description: |
    FormatoController operations for Formato
- name: formulacion
  description: |
    FormulacionController operations for Formulacion
